extends Node2D

func _ready() -> void:
	#$L0_S0.switch_act_by_id(1)
	#$L1_S1.switch_act_by_id(1)
	#$L1_S2.switch_act_by_id(1)
	#$L1_S3.switch_act_by_id(1)
	#$L1_S4.switch_act_by_id(1)
	#$L1_S5.switch_act_by_id(1)
	#$L1_S6.switch_act_by_id(1)
	#$L1_S7.switch_act_by_id(1)
	#$L1_S8.switch_act_by_id(1)
	#$L1_S9.switch_act_by_id(1)
	#$L1_S10.switch_act_by_id(1)
	#$L1_S10_R1.switch_act_by_id(1)
	#$L1_S10_R2.switch_act_by_id(1)
	#$L1_S10_R3.switch_act_by_id(1)
	#$L1_S10_R4.switch_act_by_id(1)
	#$L1_S10_L1.switch_act_by_id(1)
	
	GlobalEvent.player_follow_camera()
	await get_tree().process_frame
	get_tree().call_group(&"PLAYER_RESPAWN",&"respawn_avatar")
